version: '3.8'

services:
  seanews-api:
    build: .
    container_name: seanews-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    restart: unless-stopped
    environment:
      - AGNO_TELEMETRY=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
